### ISSUE TITLE
[CORPSE] Upload Studio

### ISSUE THREAD

**Issue by RaymanChrome** [victorfrye/microsoftgraveyard#189]
Name: Upload Studio

Free video editing software that was available on Xbox One.

It was announced on E3 on June 10th 2013.

The discontinuation was announced on September 21st 2020, followed by the release of an Xbox mobile app. It stopped working on October 30th 2020.

Microsoft E3 2013, mentioning Upload Studio - https://www.youtube.com/watch?v=OpW0qz_QE0g&t=63s 
Reddit post mentioning how they no longer support Upload Studio - https://new.reddit.com/r/xboxone/comments/jlaam4/upload_studio_discontinued_why/
Microsoft forum discussion about Upload Studio when it was discontinued - https://answers.microsoft.com/en-us/xbox/forum/all/upload-studio-no-longer-supported-trouble-trimming/b7a3823a-d8ea-4b82-b70d-050897e968ae

**Comment by victorfrye** [comment]
Nice add!  Almost forgot about Upload Studio.  Was awesome during the early times of Xbox One era.
