### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by Roslinger** [victorfrye/microsoftgraveyard#242]
**The name of the product**
Windows 10 (22H2)

**Describe the product**
Most popular OS of the years

**Initial release date of the product**
7/29/2015

**Discontinuation date of the product**
10/14/2025

**Relevant links**
https://microsoft.com/windows10

**Additional context**
it's October not November

**Comment by victorfrye** [comment]
Updated to October 10th instead of November.  Pull request and public site update should reflect this by EOD.
