### ISSUE TITLE
Interix

### ISSUE THREAD

**Issue by ForgeAus** [victorfrye/microsoftgraveyard#277]
**The name of the product**
Interix in Win2000 ->
Services for Unix (SFU) in WinXP
Subsystem for Unix-like Applications (SUA) in Win7/8?

**Describe the product**
The product added a subsystem in Windows for Unix - was deprecated from SUA
note: While it is a very different thing, some aspects of it probably survived in what is now WSL (Windows Services for Linux or if you like Ubuntu on Windows)
(Come to think of it Windows Subsystem for OS/2 in Win2000 as well is kind of fitting for this category too... )

**Initial release date of the product**
uh research it?

**Discontinuation date of the product**
Not sure - I think Win 8 or so was the last with SUA

**Relevant links**

**Additional context**

**Comment by victorfrye** [comment]
I just got back from a vacation, I'll start researching this one and should get it completed over the weekend at latest!
