### ISSUE TITLE
Missing the Microsoft Kin

### ISSUE THREAD

**Issue by sadukie** [victorfrye/microsoftgraveyard#29]
See: https://en.wikipedia.org/wiki/Microsoft_Kin

**Comment by victorfrye** [comment]
I'll get these added tonight!

**Comment by victorfrye** [comment]
I closed this and quite a few of the other issues in my latest push! Let me know if there's any others you want to see added soon (I've got a long list in Excel to research and add still) or if you find any inaccuracies! Also thank you for being the first contributor 💜
