### ISSUE TITLE
Missing Microsoft Kinect

### ISSUE THREAD

**Issue by sadukie** [victorfrye/microsoftgraveyard#34]
Not sure if you want to give it multiple gravestones, as Kinect is one of those that Microsoft keeps killing and then brings back later:

- 2017: https://www.polygon.com/2017/10/25/16543192/kinect-discontinued-microsoft-announcement
- 2018: https://gamerant.com/why-microsoft-discontinue-kinect/
- 2023: https://techcrunch.com/2023/08/22/microsoft-cant-stop-discontinuing-kinect/

**Comment by victorfrye** [comment]
I missed this one initially bc I thought they still had it living as that Azure Dev Kit.  To the graveyard it goes! Until it comes back?
