### ISSUE TITLE
Please remove Windows Phone.

### ISSUE THREAD

**Issue by IntegerMan** [victorfrye/microsoftgraveyard#39]
The death of Windows Phone is greatly exaggerated. It will return and be featured in season 2 of Firefly.

**Comment by victorfrye** [comment]
You'll ruin my surprise! I'm planning to release a major feature animating Windows Phone crawling out of its grave on the day it appears in Firefly as a marketing collaboration. Until then, it must stay in the graveyard. But don't tell anyone 🤫
