### ISSUE TITLE
Rebuild page in a mobile friendly technology stack

### ISSUE THREAD

**Issue by InDieTasten** [victorfrye/microsoftgraveyard#60]
**Is your feature request related to a problem? Please describe.**
- Initial page load is quite slow, especially on mobile
- Large (almost 800kB) page size just for rendering some non-interactive static HTML
- Page requires JavaScript execution in order to load and function
- Build / Deployment time is slow (for what this project is)

**Describe the solution you'd like**
Remove Blazor WASM dependency and utilize static site generator (like jekyll) that builds the page as a finished HTML every time the corpses.json is updated.

**Describe alternatives you've considered**
Any other static site generator.

**Additional context**
Mobile perfomance score in Lighthouse:
![image](https://github.com/victorfrye/microsoftgraveyard/assets/7047377/f3d5412c-346a-49de-9743-79ff09077e11)

I'd be happy to help with this :)

**Comment by victorfrye** [comment]
Thanks for the input. I am looking between Jekyll, Gatsby, and Next.js for SSG right now. There's justification for why this was initially built with Blazor, but as you highlight it's not performant nor the right solve for this project long term. Please bear with me as I work towards implementing this!
