### ISSUE TITLE
Software factories (.NET)

### ISSUE THREAD

**Issue by jreuben11** [victorfrye/microsoftgraveyard#71]
https://en.wikipedia.org/wiki/Software_factory_(Microsoft_.NET)
The Enterprise Framework Factory from Microsoft Services was one of the first pioneering architectural software factories to use a unique combination of model driven development, and integrated runtime environment tools to build Service-Oriented Enterprise Applications and Services.
released: 2006
killed: 2010

**Comment by victorfrye** [comment]
Do you have additional documentation and or articles for this? I've tried digging a little myself, but finding it unclear what was the Microsoft product.  I am unfamiliar with software factories, but it seems more a collection of other tooling and/or a set of patterns than a standalone product? Is there particular nostalgia for software factories?

Unfortunately, many obscure products do not have enough supporting information in their Wikipedia articles like this one, or lack one entirely.
