### ISSUE TITLE
LightSwitch Low-Code Line of Businness App Framework

### ISSUE THREAD

**Issue by jreuben11** [victorfrye/microsoftgraveyard#72]
https://learn.microsoft.com/en-us/visualstudio/productinfo/visual-studio-lightswitch-support-announcement

Microsoft Visual Studio LightSwitch was an extension and framework specifically tailored for creating line-of-business applications built on existing .NET technologies and Microsoft platforms. The applications produced were architecturally 3-tier: the user interface ran on either Microsoft Silverlight or HTML 5 client, or as a SharePoint 2013 app; the logic and data-access tier was built on WCF Data Services and exposed as an OData feed hosted in ASP.NET; and the primary data storage supported Microsoft SQL Server Express, Microsoft SQL Server and Microsoft SQL Azure. LightSwitch also supported other data sources including Microsoft SharePoint, OData and WCF RIA Services. LightSwitch included graphical designers for designing entities and entity relationships, entity queries, and UI screens. Business logic could be written in either Visual Basic or Visual C#. LightSwitch was included with Visual Studio 2012 Professional and higher. Visual Studio 2015 is the last release of Visual Studio that included the LightSwitch tooling.The first version of Visual Studio LightSwitch was released July 26, 2011. the tool was purchased and installed as a stand-alone product. As of October 14, 2016, Microsoft no longer recommends LightSwitch for new application development.

**Comment by victorfrye** [comment]
This should be already live after #66. Also see comments there for dates.
