### ISSUE TITLE
Windows Workflow Foundation

### ISSUE THREAD

**Issue by jreuben11** [victorfrye/microsoftgraveyard#74]
Windows Workflow Foundation was a Microsoft technology that provided an API, an in-process workflow engine, and a rehostable designer to implement long-running processes as workflows within .NET applications. The last version of WF was released as part of the .NET Framework version 4.5 in 2012. It was not brought forward into .NET Core. A workflow was a series of distinct programming steps or phases. Each step is modeled in WF as an Activity. The .NET Framework provided a library of activities. Custom activities can also be developed for additional functionality. Activities could be assembled visually into workflows using the Workflow Designer, a design surface that ran within Visual Studio. The designer could also be hosted in other applications. Encapsulating programming functionality into the activities allowed the developer to create more manageable applications; each component of execution can be developed as a Common Language Runtime object whose execution will be managed by the workflow runtime.
links:
- https://en.wikipedia.org/wiki/Windows_Workflow_Foundation
- https://andreioros.com/blog/windows-workflow-foundation-net-core/

Initial release:	November 21, 2006; 17 years ago
last release: August 15, 2012; 11 years ago

this framework has since been abandoned - it is not part of .NET 5 onwards
In 2019, Microsoft re-emphasized that .Net Core is the future of .Net and that WF will not be a part of it, forwarding interested parties to the [open-source community project](https://devblogs.microsoft.com/dotnet/supporting-the-community-with-wf-and-wcf-oss-projects/).

**Comment by victorfrye** [comment]
So this one is a tricky aspect.  .NET Framework is not dead and although there's a ton of different products that are being abandoned in Core and .NET 6+, many are still on life support with .NET framework with a commitment from Microsoft to still support and bundle .NET Framework with Windows.

Until it is actually killed off, it is not "dead" and therefore not ready for the graveyard. Frequently this means extended maintenance support has an announced end.
